name: Minify JavaScript

on:
  push:
    paths:
      - 'TM.js'

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install terser -g
    - name: Minify
      run: terser TM.js -o TM.auto.min.js
    - name: Commit minified file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add TM.auto.min.js
        git commit -m "Auto-minify TM.js" || exit 0
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
